### ISSUE TITLE
Не робе, + панікує при натисканні стрілки вниз коли 0 пунктів меню

### ISSUE THREAD

**Issue by haski007** [irevenko/tiktik#2]
```
fatal-1
fatal-1
fatal-1
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/gizak/termui/v3/widgets.(*List).Draw(0x14000230360, 0x1400010d4d0)
	/Users/demian/go/pkg/mod/github.com/gizak/termui/v3@v3.1.0/widgets/list.go:47 +0x4e4
github.com/gizak/termui/v3.Render({0x1400011dc80?, 0x2, 0x3?})
	/Users/demian/go/pkg/mod/github.com/gizak/termui/v3@v3.1.0/render.go:25 +0x148
github.com/irevenko/tiktik/tui.SetupTUI({0x0, 0x0, 0x1400011df28?}, {0x0, 0x0, 0x104c938c0?}, {0x0, 0x0, 0x14000044768?}, {0x0, ...}, ...)
	/Users/demian/tiktik/tui/tui.go:100 +0x994
main.main()
	/Users/demian/tiktik/main.go:15 +0x24
```

**Comment by irevenko** [comment]
давно не дивився схоже що тікток змінили щось у себе в коді

**Comment by haski007** [comment]
Да, вже ото що було в html коді сторінки з відео атрибут "downloadAddr"  з лінкою на оригінал відео - вже плюється 403 помилкою 👎  :(

**Comment by Administration124** [comment]
fatal-1
fatal-1
fatal-1
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/gizak/termui/v3/widgets.(*List).Draw(0x14000230360, 0x1400010d4d0)
	/Users/demian/go/pkg/mod/github.com/gizak/termui/v3@v3.1.0/widgets/list.go:47 +0x4e4
github.com/gizak/termui/v3.Render({0x1400011dc80?, 0x2, 0x3?})
	/Users/demian/go/pkg/mod/github.com/gizak/termui/v3@v3.1.0/render.go:25 +0x148
github.com/irevenko/tiktik/tui.SetupTUI({0x0, 0x0, 0x1400011df28?}, {0x0, 0x0, 0x104c938c0?}, {0x0, 0x0, 0x14000044768?}, {0x0, ...}, ...)
	/Users/demian/tiktik/tui/tui.go:100 +0x994
main.main()
	/Users/demian/tiktik/main.go:15 +0x24
